package com.se.goBears.entity;

import lombok.Data;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;

/**
 * This entity class defines the methods and variables for the entity allotment. Allotment defines all the room
 * and date allotments to a user.
 */
@Data
@Entity
public class Allotment implements Serializable {
    /**
     * This variable annotated with @ID and @GeneratedValue defines an autogenerated id for entity objects.
     */
    @Id
    @GeneratedValue
    private Long id;

    /**
     * This variable annotated with @ManyToOne defines a ManyToOne relationship with Room entity.
     */
    @ManyToOne
    private Room room;

    /**
     * This variable defies a start date for an allotment.
     */
    private Date fromDate;
    /**
     * This variable defines a end date for an allotment.
     */
    private Date toDate;

    /**
     * This variable annotated with @OneToOne defines a OneToOne relationship with User entity.
     */
    @OneToOne
    private User user;


}
