package com.se.goBears.entity;

import lombok.Data;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Set;

/**
 * This entity class defines the methods and variables for the entity Building. Building defines all the buildings
 * information.
 */
@Data
@Entity
public class Building implements Serializable {

    /**
     * This variable annotated with @ID and @GeneratedValue defines an autogenerated id for entity objects.
     */
    @Id
    @GeneratedValue
    private Long id;
    /**
     * This variable defines the name for the building.
     */
    private String name;

    /**
     * This variable annotated with @OneToOne defines a OneToOne relationship with Address entity.
     */
    @OneToOne
    private Address address;

    /**
     * The variable defines the number of floors in the building.
     */
    private Integer floors;

    /**
     * This variable defines the latitude for the building.
     */
    private Double latitude;

    /**
     * This variable defines the longitude for the building.
     */
    private Double longitude;

    /**
     * This variable annotated with @OneToMany defines a OneToMany relationship with Gate entity.
     */
    @OneToMany
    private Set<Gate> gate;

    /**
     * This variable annotated with @OneToMany defines a OneToMany relationship with Room entity.
     */
    @OneToMany
    private Set<Room> rooms;

}
