package com.se.goBears.entity;

import javax.persistence.*;

/**
 * This entity class defines the methods and variables for the entity Direction. Direction defines all the direction
 * description to a specified room.
 */
public class Direction {

    /**
     * This variable annotated with @ID and @GeneratedValue defines an autogenerated id for entity objects.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", nullable = false)
    private Long id;

    /**
     * This variable defines the description for the direction to a room.
     */
    private String description;

    /**
     * This variable annotated with @OneToOne defines a OneToOne relationship with Room entity.
     */
    @OneToOne
    private Room room;
}
