package com.se.goBears.entity;

import javax.persistence.*;

/**
 * This entity class defines the methods and variables for the entity Reservations. Reservation defines all the
 * description for the reservations.
 */
@Entity
public class Reservations {

    /**
     * This variable annotated with @ID and @GeneratedValue defines an autogenerated id for entity objects.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", nullable = false)
    private Long id;


    /**
     * This variable defines the id of the user associated with the reservation.
     */
    private Integer bookedBy;

    /**
     * The variable defines the start date for the reservation.
     */
    private String fromDate;

    /**
     * This variable defines the end date for the reservation.
     */
    private String toDate;

    /**
     * This variable defines the room associated with the reservation.
     */
    private long roomId;

    /**
     * This method returns the room id associated with the reservation.
     *
     * @return is of the room associated with the reservation.
     */
    public long getRoomId() {
        return roomId;
    }

    /**
     * This method sets the value for room id for a reservation.
     *
     * @param roomId is the room id to be associated to the reservation.
     */
    public void setRoomId(long roomId) {
        this.roomId = roomId;
    }

    /**
     * This variable defines the status of a reservation.
     */
    private Status status = Status.PENDING;

    /**
     * This enum class status defines the valid status for a reservation.
     */
    public enum Status {
        PENDING, DECLINED, APPROVED, ARCHIVED, CANCELED
    }

    /**
     * The variable defines the type of the reservation
     */
    private ReserveType reserveType;

    /**
     * This enum class defines the possible type for the reservation i.e room or a resource.
     */
    public enum ReserveType {
        Room, Resource
    }

    /**
     * This method returns the id of a reservation.
     *
     * @return id of a reservations.
     */
    public Long getId() {
        return id;
    }

    /**
     * This method sets an id for a reservation.
     *
     * @param id is the id to be set.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method returns the user id of the person associated with the reservation.
     *
     * @return user id of the person associated with the reservation.
     */
    public Integer getBookedBy() {
        return bookedBy;
    }

    /**
     * This method sets the user to be associated with the reservation.
     *
     * @param bookedBy is the id of the user to be associated with the reservation.
     */
    public void setBookedBy(Integer bookedBy) {
        this.bookedBy = bookedBy;
    }

    /**
     * This method returns the start date for the reservation.
     *
     * @return start date for a reservation.
     */
    public String getFromDate() {
        return fromDate;
    }

    /**
     * This method sets the start date for a reservation.
     *
     * @param fromDate is the start date of a reservation.
     */
    public void setFromDate(String fromDate) {
        this.fromDate = fromDate;
    }

    /**
     * This method returns the end date for a reservation.
     *
     * @return end date for a reservation.
     */
    public String getToDate() {
        return toDate;
    }

    /**
     * This method sets the end date for a reservation,
     *
     * @param toDate is the end date to be set,
     */
    public void setToDate(String toDate) {
        this.toDate = toDate;
    }

    /**
     * The method returns the status of a reservation.
     *
     * @return the status of a reservation.
     */
    public Status getStatus() {
        return status;
    }

    /**
     * The method sets the status of a reservation.
     *
     * @param is the status to be set.
     */
    public void setStatus(Status status) {
        this.status = status;
    }

    /**
     * This method returns the reservation type.
     *
     * @return the type of reservation i.e. room or resource.
     */
    public ReserveType getReserveType() {
        return reserveType;
    }

    /**
     * This method sets the type of reservation.
     *
     * @param reserveType is the reservation type to be set.
     */
    public void setReserveType(ReserveType reserveType) {
        this.reserveType = reserveType;
    }
}
