package com.se.goBears.entity;

import com.se.goBears.enums.ERole;

import javax.persistence.*;
import java.io.Serializable;

/**
 * This entity class defines the methods and variables for the entity Role. Role defines all the
 * description for the user roles.
 */
@Entity
@Table(name = "roles")
public class Role implements Serializable {

    /**
     * This variable annotated with @ID and @GeneratedValue defines an autogenerated id for entity objects.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * This variable annotated with @Enumerated defines the name for a role.
     */
    @Enumerated(EnumType.STRING)
    @Column(length = 20)
    private ERole name;

    public Role() {

    }

    /**
     * This method set the role name.
     *
     * @param name is the name of the role.
     */
    public Role(ERole name) {
        this.name = name;
    }

    /**
     * This method returns the id for the role.
     *
     * @return id for the role.
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method sets the id for a role.
     *
     * @param id is the id to be set.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method returns the name of the role.
     *
     * @return the name of the role.
     */
    public ERole getName() {
        return name;
    }

    /**
     * This method set the role name.
     *
     * @param name is the name of the role.
     */
    public void setName(ERole name) {
        this.name = name;
    }
}
