package com.se.goBears.entity;


import javax.persistence.*;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * This entity class defines the methods and variables for the entity Room. Room defines all the
 * description for the room.
 */
@Entity
public class Room implements Serializable {

    /**
     * This variable annotated with @ID and @GeneratedValue defines an autogenerated id for entity objects.
     */
    @Id
    @GeneratedValue
    private Long id;

    /**
     * this variable defines the name for a room.
     */
    private String name;
    /**
     * This variable defines the room type.
     */
    private RoomType roomType;
    /**
     * This boolean variable define if the room is bookable.
     */
    private boolean isBookable;

    /**
     * This variable annotated with @OneToMany defines a OneToMany relationship with Reservations entity.
     */
    @OneToMany(targetEntity = Reservations.class, cascade = CascadeType.ALL)
    private Set<Reservations> roomReservation = new HashSet<>();

    /**
     * This variable annotated with @ManyToOne defines a ManyToOne relationship with Building entity.
     */
    @ManyToOne
    private Building building;

    /**
     * This variable annotated with @OneToMany defines a OneToMany relationship with Users entity.
     */
    @OneToMany
    private Set<User> users = new HashSet<>();


    /**
     * This variable defines the latitude of a room.
     */
    private Long latitude;

    /**
     * This variable defines the longitude of a room.
     */
    private Long Longitude;


    /**
     * This enum class defines the possible type of room.
     */
    public enum RoomType {
        classroom, staffroom, lab, washroom
    }

    /**
     * This method returns the id of the room.
     *
     * @return id of the room.
     */
    public Long getId() {
        return id;
    }

    /**
     * This method sets the id of the room.
     *
     * @param id is the id of the room.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method returns the name of the room.
     *
     * @return the room name.
     */
    public String getName() {
        return name;
    }

    /**
     * This method sets the name of the room.
     *
     * @param name is the name of the room
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method returns the room type.
     *
     * @return the type of the room.
     */
    public RoomType getRoomType() {
        return roomType;
    }

    /**
     * This method sets the room type.
     *
     * @param roomType the room type to be set.
     */
    public void setRoomType(RoomType roomType) {
        this.roomType = roomType;
    }


    /**
     * This method returns if the room is bookable.
     *
     * @return the bookable status of a room.
     */
    public boolean isBookable() {
        return isBookable;
    }


    /**
     * This method sets the bookable status of a room.
     *
     * @param isBookable is the status to be set.
     */
    public void setIsBookable(boolean isBookable) {
        this.isBookable = isBookable;
    }

    /**
     * This method returns a set of all reservations associated with a room.
     *
     * @return a set of reservation.
     */
    public Set<Reservations> getRoomReservation() {
        return roomReservation;
    }

    /**
     * This method sets a reservation for a room.
     *
     * @param roomReservation id the reservation to be set.
     */
    public void setRoomReservation(Set<Reservations> roomReservation) {
        this.roomReservation = roomReservation;
    }

    /**
     * This method returns the building associated with the room.
     *
     * @return the building.
     */
    public Building getBuilding() {
        return building;
    }

    /**
     * This method sets the building to be associated with a room.
     *
     * @param building is the building to be set.
     */
    public void setBuilding(Building building) {
        this.building = building;
    }

    /**
     * This method gets a set of user associated with a room.
     *
     * @return a set of users.
     */
    public Set<User> getUsers() {
        return users;
    }

    /**
     * This method sets the user to be associated with a toom.
     *
     * @param users is a set of users.
     */
    public void setUsers(Set<User> users) {
        this.users = users;
    }

    /**
     * This method returns the latitude of a room.
     *
     * @return latitude value.
     */
    public Long getLatitude() {
        return latitude;
    }

    /**
     * This method sets the latitude value for a room.
     *
     * @param latitude is the latitude to be set.
     */
    public void setLatitude(Long latitude) {
        this.latitude = latitude;
    }

    /**
     * This method returns the longitude of a room.
     *
     * @return longitude value.
     */
    public Long getLongitude() {
        return Longitude;
    }

    /**
     * This method sets the longitude value for a room.
     *
     * @param longitude is the longitude to be set.
     */
    public void setLongitude(Long longitude) {
        Longitude = longitude;
    }
}
