package com.se.goBears.entity;

import lombok.Data;

import javax.persistence.*;
import java.util.Date;

/**
 * This entity class defines the methods and variables for the entity Schedule. Schedule defines all the
 * description for the schedule.
 */
@Data
@Entity
public class Schedule {

    /**
     * This variable annotated with @ID and @GeneratedValue defines an autogenerated id for entity objects.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", nullable = false)
    private Long id;

    /**
     * This variable defines the name of the schedule.
     */
    private String name;
    /**
     * This variable defines the start date of the schedule.
     */
    private Date fromDate;
    /**
     * This variable defines the end date of the schedule.
     */
    private Date toDate;

    /**
     * This variable annotated with @ManyToOne defines a ManyToOne relationship with Room entity.
     */
    @ManyToOne
    private Room room;


}
